name: Scheduled Update
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
    updater:
      runs-on: ubuntu-latest
      name: Updating GameZone data
      steps:
        - uses: actions/checkout@v2
        - uses: r-lib/actions/setup-r@v1
          with:
            r-version: ${{ matrix.r-version }}
        - name: Install base dependencies
          run: |
            Rscript -e 'install.packages(c("tidyverse","glue","stringr"))'
            Rscript -e 'remotes::install_github(repo = "saiemgilani/cfbfastR")'
          env:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        - name: Pull data and update files
          run: Rscript ./team_agg.R
        - name: Push updated files
          uses: test-room-7/action-update-file@v1.5.0
          with:
            file-path: ./data/**/*
            commit-msg: "Updated team summaries after latest bot run."
            github-token: ${{ secrets.GITHUB_TOKEN }}