name: Skeet Post-Week Content

on:
  schedule:
    - cron: "0 15 * 8-12 1" # Run at 10am every Monday from August through December.
    # - cron: "0 15 * 1 1" # Run at 10am every Monday in January
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: '4.3'
        - run: Rscript ./team_agg.R
          env:
            CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        - run: Rscript ./postweek.R
          env:
            CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
            BLUESKY_APP_USER: ${{ secrets.BLUESKY_APP_USER }}
            BLUESKY_APP_PASS: ${{ secrets.BLUESKY_APP_PASS }}
            SKEET_ENVIRONMENT: test

