name: Skeet Game Previews

on:
  schedule:
    - cron: "0 15 * 9-11 6" # run 10am on Sat from Sept-Nov (normal)
    - cron: "0 23 * 9-11 1-5" # run 6pm on non-Sat/Sun from Sept-Nov (MACtion, ACC, Black Friday)
    # - cron: "0 15 * 12 *" # run at 10am every day in December (bowls)
    # - cron: "0 15 1-16 1 *" # run at 10am every day from Jan 1-16 (playoff)
    # - cron: "0 15 20-31 8 *" # run at 10am every day from Aug 20-31 (Week 0)
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: '4.3'
            use-public-rspm: true
        - name: Install packages
          uses: r-lib/actions/setup-r-dependencies@v2
          with:
            packages: |
                any::tidyverse
                any::stringr
                any::glue
                any::devtools
                any::glmnet
                any::webshot2
                any::gt
                any::gtExtras
                any::magick
                github::sportsdataverse/cfbfastR
                github::andreweatherman/cbbdata
                github::andreweatherman/cbbplotR
                github::Kazink36/cfbplotR
                github::christopherkenny/bskyr
        - run: Rscript ./team_agg.R
          env:
            CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        - run: Rscript ./previews.R
          env:
            CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
            BLUESKY_APP_USER: ${{ secrets.BLUESKY_APP_USER }}
            BLUESKY_APP_PASS: ${{ secrets.BLUESKY_APP_PASS }}
            SKEET_ENVIRONMENT: test

